### ISSUE TITLE
[Videos] Separate videos from text articles

### ISSUE THREAD

**Issue by pgte** [hubbleio/hubble.io#12]
First, design, then development. :)

**Comment by thefoxis** [comment]
So what exactly do you need?

**Comment by pgte** [comment]
(requested by @dscape)

Design videos "section" and how the navigation will work with this new section.

**Comment by thefoxis** [comment]
Separate page? I'm not exactly sure about contents. Thoughts?

**Comment by pgte** [comment]
I'd say the page template would be the same as a category page, listing all videos, latest first. It's just another filter over the articles.  

What do you say?

**Comment by thefoxis** [comment]
Hmm. I'd float the videos, like for example 4 per row with some meta information and tags. Let me prepare a quick mockup.

If it comes to the master navigation - we need to rethink it. It's not going to work properly on mobile at all. We need different solution.

**Comment by thefoxis** [comment]
So my proposal is to at home page use [labels](http://twitter.github.com/bootstrap/components.html#labels) for posts with videos. 

We can show video listing like that (check the link below). So basically four videos per row and filtering through date. If we want to show how long ago the videos were publish I'd suggest adding a filtering mechanism too (and naturally search). But this can be added later.

Other thing to figure out is how the videos will be played. Do we need a separate page for each video or it would be enough to enlarge the box container and then play the video. Thoughts?

[Category page for videos](https://www.dropbox.com/s/c4kpoe2m5a8hhj6/nodeguides-videos.png)

PS. Are we using Vimeo or Youtube? Personally I prefer Vimeo for embedding and overall UI. But I guess we're going with Youtube.
