### ISSUE TITLE
[Category] Title should be link, longer description

### ISSUE THREAD

**Issue by thefoxis** [hubbleio/hubble.io#13]
On each category page the title should be a link to the full article. It's extremely annoying to have to go all the way to the button. Both should be used as a way for seeing the content.

Longer description should be displayed. Two to three sentences. Now it's simply too short and doesn't look nice.

**Comment by pgte** [comment]
1e485f2 solves article link in list view.

Regarding description size, the descriptions are article meta-data, have to be solved by producing more content for each article. Created #23 for this.
