### ISSUE TITLE
[Article] Content expansion

### ISSUE THREAD

**Issue by thefoxis** [hubbleio/hubble.io#14]
On each article page there's an icon which allows the user to expand the content column to full width. First of all, there's **no way to go back from full width to the original layout**, it's a serious UX flaw. Secondly the sidebar should have `margin-top` when dropped, and currently it doesn't.

Do we really need that feature? I think that the content column is wide enough.

**Comment by pgte** [comment]
@karolinaszczur: @dscape is not of that opinion, he requested the feature. :)

It was experimental.
I can add a retraction button after it's expanded, or I can drop the feature altogether.

@dscape ?

**Comment by dscape** [comment]
I requested a link the readability version of the article :) I love readability, and think its a great service (Especially on tablets etc).

We shouldn't do any UX flaws, this is supposed to be an UX enhancement :)

**Comment by dscape** [comment]
e.g. http://www.readability.com/articles/cfp6fjrf

**Comment by thefoxis** [comment]
Yeah. Let's go with Readability and ditch the full-width option.

**Comment by pgte** [comment]
Readability integrated here: 4a9da6423f0639c343a68993a88a1be9ead256e2

When I'm capable of deploying you can check it out.
