### ISSUE TITLE
[Article] Improvements

### ISSUE THREAD

**Issue by thefoxis** [hubbleio/hubble.io#16]
- Heading: Add more `margin-bottom`, increase `line-height` in heading
- Paragraphs: Decrease `line-height`
- Add _tip_ tag styling
- Spacing and styling in sidebar buttons
- Author articles styling to be improved
- Previous button styling
- Breadcrumbs styling

@pgte - if there's no Twitter account for each author Github icon should be aligned more to the left, along with the name

**Comment by pgte** [comment]
> @pgte - if there's no Twitter account for each author Github icon should be aligned more to the left, along with the name

@karolinaszczur: That's taken care of.
