### ISSUE TITLE
[Article submission] Category selection

### ISSUE THREAD

**Issue by thefoxis** [hubbleio/hubble.io#22]
The styling for dropdown is different than level dropdown. Moreover it's really hard to navigate. It causes another scrollbar to appear and it's very inconvenient for browsing. 

Maybe different solution should be considered (since we're using Bootstrap maybe Typehead plugin would be better).

**Comment by pgte** [comment]
I think that we should resort to a regular HTML select, it would probably obviate these problems.

On the other hand, maybe we should remove category and level selection altogether, and leave the categorization and difficulty attribution to the moderator.

I vote for the latest.

@karolinaszczur what do you say?

**Comment by thefoxis** [comment]
Yeah, for sure level should be chosen by the moderator, he will have better judgement. Topic could be chosen via typehead. We don't want to swamp moderators with unnecessary work :)

**Comment by pgte** [comment]
An article can be in more than one topic, so the moderator will always have to review it.
I think we should remove the input box altogether, and introduce it later if and when we get a better feeling of the moderation workflow improvements we can introduce.

**Comment by thefoxis** [comment]
I agree, we can add that feature later and keep it simple for now.
