### ISSUE TITLE
[Watch Article] Star and Watch?

### ISSUE THREAD

**Issue by pgte** [hubbleio/hubble.io#24]
As of now, the "watch it" button on an article triggers a github watch, but I think we should support the new "star" system in Github.

Either as an alternative or in complement.

@karolinaszczur what do you think?

**Comment by thefoxis** [comment]
I guess we should, to maintain consistency. I need to dive a little bit into the new system because I vaguely remember the idea of staring.

**Comment by pgte** [comment]
@karolinaszczur it's a new thing: https://github.com/blog/1204-notifications

**Comment by thefoxis** [comment]
I think we should probably go with both. Altough I'm not extra sure about the interaction that should be going on. 

Do you think that people will be willing to just track the changes? I think if they're not contributing they would want only a feed of new articles, not every change within every article.

**Comment by pgte** [comment]
I think we should go with star only.
If people want to follow they can do it in github directly.

@karolinaszczur can you change the logo, I'll change the back-end code?

**Comment by thefoxis** [comment]
On the single article page only, right?

**Comment by pgte** [comment]
Yes, but wait, the "starring" is not yet supported on the github API.
We'll have to stick to "watching" for now :(

**Comment by thefoxis** [comment]
Closing for now since it's not relevant.
