### ISSUE TITLE
[Mobile] Bugs and improvements

### ISSUE THREAD

**Issue by thefoxis** [hubbleio/hubble.io#25]
**Mobile in general**
- Consider replacing modals with separate subpages for mobile
- Navigation should fit the resolution
- Fix Bootstrap navigation solution on smaller resolutions - it won't work with submenus
- Scale logo accordingly to resolution

**Tablet (vertical)**
- [Home] Move Github button to the right so that intro text and the button will be in one line

**Tablet (horizontal)**
- [General] Footer navigation missing

**Mobile (vertical)**
- **[General] remove padding left and right on content**
- [Home] Resize font in intro, make button smaller
- **[Home] Fix the padding on footer navigation**

@pgte you can help with those, just cross them off the list when they're fixed please :)

Bolded bugs are done.

**Comment by pgte** [comment]
@karolinaszczur, I'm going to assign this to you, ok? Perhaps I can give you a hand later, but now I'm busy with the rest of the missing stuff. :)

**Comment by thefoxis** [comment]
Sure!
