### ISSUE TITLE
[General] Footer links

### ISSUE THREAD

**Issue by pgte** [hubbleio/hubble.io#6]
Update footer links, customizable in conf.json for:
- Twitter
- Github

**Comment by thefoxis** [comment]
Also: 
- the color of icons in footer is wrong, it should be grey 
- bigger hubble.io logo
- add Nodejitsu logo

(I will cover this)

**Comment by pgte** [comment]
Twitter and Github links are done.

**Comment by thefoxis** [comment]
Fixed in [830d84a7f5](https://github.com/hubbleio/hubble.io/commit/830d84a7f5ba85aa33c1c450bdc8a73947829bf1).
